AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
Layout/LineLength:
  Max: 181
Metrics/BlockLength:
  Max: 195
Metrics/ClassLength:
  Max: 209
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/qa/local_authority.rb'
    - 'app/models/qa/local_authority_entry.rb'
    - 'test/test_helper.rb'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/hyrax_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/ability.rb'
    - 'app/models/application_record.rb'
    - 'app/models/qa.rb'
    - 'app/models/qa/local_authority_entry.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/solr_document.rb'
    - 'app/models/user.rb'
    - 'config/application.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
    - 'spec/features/create_item_spec.rb'

