version: '2.1'
services:
  app:
    build: docker/app
    image: hyrax_app
    ports:
      - "3000"
    volumes:
      - .:/opt/hyrax
      - gems:/opt/bundle
    depends_on:
      - redis
      - fcrepo
      - solr
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      HYRAX_DB_HOST: db
      DOCKER_HOST_HOSTNAME: $DOCKER_HOST_HOSTNAME
  worker:
    image: hyrax_app
    depends_on:
      - db
      - redis
      - app
    volumes_from:
      - app
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      HYRAX_REDIS_HOST: redis
      HYRAX_REDIS_PORT: 6379
      HYRAX_URL: http://app:3000
      QUEUE: "*"
    command: sidekiq
  db:
    image: mysql:5
    ports:
      - "5432:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hyrax
    volumes:
      - mysqldata:/var/lib/mysql
  fcrepo_db:
    image: mysql:5
    ports:
      - "3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fcrepo
    volumes:
      - fcrepo_db:/var/lib/mysql
    healthcheck:
      test: mysql -h fcrepo_db -u root --password=root fcrepo --execute "SHOW DATABASES;"
      interval: 30s
      timeout: 30s
      retries: 5
  cantaloupe:
    build: docker/cantaloupe
    ports:
      - "8182:8182"
    volumes:
      - cantaloupe:/var/
    depends_on:
      - fcrepo
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379"
    volumes:
      - redis:/data
  solr:
    build: solr
    ports:
      - "8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
  fcrepo:
    build: docker/fcrepo
    ports:
      - "8984"
    depends_on:
      fcrepo_db:
        condition: service_healthy
    volumes:
      - fcrepo:/opt/fcrepo/data
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    depends_on:      
      - app    
    ports:      
      - "3010:80"
volumes:
  cantaloupe:
  fcrepo:
  fcrepo_db:
  gems:
  mysqldata:
  redis:
  solr:
networks:
  default:
    driver: bridge
