#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#
analytics:
  app_name: GOOGLE_OAUTH_APP_NAME
  app_version: GOOGLE_OAUTH_APP_VERSION
  privkey_path: <%= ENV["UC_DRC_ANALYTICS_PRIVKEY_PATH"] %>
  privkey_secret: <%= ENV["UC_DRC_ANALYTICS_PRIVKEY_SECRET"] %>
  client_email: <%= ENV["UC_DRC_ANALYTICS_CLIENT_EMAIL"] %>
